<a href="https://colab.research.google.com/github/tacianoamorim/DO180-apps/blob/master/%5Bexp%5D%5BYAHOOQUERY%5D.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Project description**
Yahooquery is a python interface to unofficial Yahoo Finance API endpoints. The package allows a user to retrieve nearly all the data visible via the Yahoo Finance front-end.

Some features of yahooquery:

Fast: Data is retrieved through API endpoints instead of web scraping. Additionally, asynchronous requests can be utilized with simple configuration
Simple: Data for multiple symbols can be retrieved with simple one-liners
User-friendly: Pandas Dataframes are utilized where appropriate
Premium: Yahoo Finance premium subscribers are able to retrieve data 
available through their subscription

https://pypi.org/project/yahooquery/

Guide: https://yahooquery.dpguthrie.com/

## The Ticker module

In [2]:
!pip install yahooquery

from yahooquery import Ticker

Collecting yahooquery
  Downloading yahooquery-2.2.15-py2.py3-none-any.whl (46 kB)
     |████████████████████████████████| 46 kB 2.8 MB/s
Collecting requests-futures>=1.0.0
  Downloading requests_futures-1.0.0-py2.py3-none-any.whl (7.4 kB)
Requirement already satisfied: pandas>=0.24.0 in /usr/local/lib/python3.7/dist-packages (from yahooquery) (1.3.5)
Collecting lxml>=4.6.2
  Downloading lxml-4.8.0-cp37-cp37m-manylinux_2_17_x86_64.manylinux2014_x86_64.manylinux_2_24_x86_64.whl (6.4 MB)
     |████████████████████████████████| 6.4 MB 14.8 MB/s
Requirement already satisfied: tqdm>=4.54.1 in /usr/local/lib/python3.7/dist-packages (from yahooquery) (4.64.0)
Requirement already satisfied: pytz>=2017.3 in /usr/local/lib/python3.7/dist-packages (from pandas>=0.24.0->yahooquery) (2022.1)
Requirement already satisfied: numpy>=1.17.3 in /usr/local/lib/python3.7/dist-packages (from pandas>=0.24.0->yahooquery) (1.21.6)
Requirement already satisfied: python-dateutil>=2.7.3 in /usr/local/lib/python3.7/dist-packages (from pandas>=0.24.0->yahooquery) (2.8.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.7/dist-packages (from python-dateutil>=2.7.3->pandas>=0.24.0->yahooquery) (1.15.0)
Requirement already satisfied: requests>=1.2.0 in /usr/local/lib/python3.7/dist-packages (from requests-futures>=1.0.0->yahooquery) (2.23.0)
Requirement already satisfied: chardet<4,>=3.0.2 in /usr/local/lib/python3.7/dist-packages (from requests>=1.2.0->requests-futures>=1.0.0->yahooquery) (3.0.4)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /usr/local/lib/python3.7/dist-packages (from requests>=1.2.0->requests-futures>=1.0.0->yahooquery) (1.24.3)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.7/dist-packages (from requests>=1.2.0->requests-futures>=1.0.0->yahooquery) (2021.10.8)
Requirement already satisfied: idna<3,>=2.5 in /usr/local/lib/python3.7/dist-packages (from requests>=1.2.0->requests-futures>=1.0.0->yahooquery) (2.10)
Installing collected packages: requests-futures, lxml, yahooquery
  Attempting uninstall: lxml
    Found existing installation: lxml 4.2.6
    Uninstalling lxml-4.2.6:
      Successfully uninstalled lxml-4.2.6
Successfully installed lxml-4.8.0 requests-futures-1.0.0 yahooquery-2.2.15

In [3]:
aapl = Ticker('aapl')
aapl.summary_detail

{'aapl': {'algorithm': None,
  'ask': 168.98,
  'askSize': 800,
  'averageDailyVolume10Day': 74511420,
  'averageVolume': 91570504,
  'averageVolume10days': 74511420,
  'beta': 1.187745,
  'bid': 0.0,
  'bidSize': 800,
  'currency': 'USD',
  'dayHigh': 168.86,
  'dayLow': 166.1,
  'dividendRate': 0.88,
  'dividendYield': 0.0053,
  'exDividendDate': '2022-02-04 00:00:00',
  'fiftyDayAverage': 167.4436,
  'fiftyTwoWeekHigh': 182.94,
  'fiftyTwoWeekLow': 122.25,
  'fiveYearAvgDividendYield': 1.11,
  'forwardPE': 25.453575,
  'fromCurrency': None,
  'lastMarket': None,
  'marketCap': 2729093103616,
  'maxAge': 1,
  'open': 168.76,
  'payoutRatio': 0.1434,
  'previousClose': 167.4,
  'priceHint': 2,
  'priceToSalesTrailing12Months': 7.213659,
  'regularMarketDayHigh': 168.86,
  'regularMarketDayLow': 166.1,
  'regularMarketOpen': 168.76,
  'regularMarketPreviousClose': 167.4,
  'regularMarketVolume': 66275582,
  'toCurrency': None,
  'tradeable': False,
  'trailingAnnualDividendRate': 0.865,
  'trailingAnnualDividendYield': 0.0051672645,
  'trailingPE': 27.80216,
  'twoHundredDayAverage': 158.771,
  'volume': 66275582}}

In [18]:
aapl.price

{'aapl': {'currency': 'USD',
  'currencySymbol': '$',
  'exchange': 'NMS',
  'exchangeDataDelayedBy': 0,
  'exchangeName': 'NasdaqGS',
  'fromCurrency': None,
  'lastMarket': None,
  'longName': 'Apple Inc.',
  'marketCap': 2729093103616,
  'marketState': 'PRE',
  'maxAge': 1,
  'postMarketChange': 0.630005,
  'postMarketChangePercent': 0.0037673,
  'postMarketPrice': 167.86,
  'postMarketSource': 'FREE_REALTIME',
  'postMarketTime': 1650499199,
  'preMarketChange': 1.75,
  'preMarketChangePercent': 0.01046463,
  'preMarketPrice': 168.98,
  'preMarketSource': 'FREE_REALTIME',
  'preMarketTime': '2022-04-21 12:50:59',
  'priceHint': 2,
  'quoteSourceName': 'Nasdaq Real Time Price',
  'quoteType': 'EQUITY',
  'regularMarketChange': -0.16999817,
  'regularMarketChangePercent': -0.0010155208,
  'regularMarketDayHigh': 168.86,
  'regularMarketDayLow': 166.1,
  'regularMarketOpen': 168.76,
  'regularMarketPreviousClose': 167.4,
  'regularMarketPrice': 167.23,
  'regularMarketSource': 'FREE_REALTIME',
  'regularMarketTime': '2022-04-20 20:00:04',
  'regularMarketVolume': 66275582,
  'shortName': 'Apple Inc.',
  'symbol': 'AAPL',
  'toCurrency': None,
  'underlyingSymbol': None}}

In [17]:
aapl.quote_type

{'aapl': {'exchange': 'NMS',
  'firstTradeDateEpochUtc': '1980-12-12 14:30:00',
  'gmtOffSetMilliseconds': -14400000,
  'longName': 'Apple Inc.',
  'maxAge': 1,
  'messageBoardId': 'finmb_24937',
  'quoteType': 'EQUITY',
  'shortName': 'Apple Inc.',
  'symbol': 'AAPL',
  'timeZoneFullName': 'America/New_York',
  'timeZoneShortName': 'EDT',
  'underlyingSymbol': 'AAPL',
  'uuid': '8b10e4ae-9eeb-3684-921a-9ab27e4d87aa'}}

In [16]:
df = aapl.history(start='2020-01-01')
df.head()

                        open     volume       high        low      close  \
symbol date
aapl   2020-01-02  74.059998  135480400  75.150002  73.797501  75.087502
       2020-01-03  74.287498  146322800  75.144997  74.125000  74.357498
       2020-01-06  73.447502  118387200  74.989998  73.187500  74.949997
       2020-01-07  74.959999  108872000  75.224998  74.370003  74.597504
       2020-01-08  74.290001  132079200  76.110001  74.290001  75.797501

                    adjclose  dividends  splits
symbol date
aapl   2020-01-02  73.894325        0.0     0.0
       2020-01-03  73.175934        0.0     0.0
       2020-01-06  73.759010        0.0     0.0
       2020-01-07  73.412102        0.0     0.0
       2020-01-08  74.593040        0.0     0.0

In [15]:
df = aapl.history(period='2d')
df.head()

                        close    volume        open        high         low  \
symbol date
aapl   2022-04-19  167.399994  67723800  165.020004  167.820007  163.910004
       2022-04-20  167.229996  67828800  168.759995  168.880005  166.100006

                     adjclose
symbol date
aapl   2022-04-19  167.399994
       2022-04-20  167.229996

In [14]:
df = aapl.history(period='1mo', interval='5m')
df

                             volume        high        open       close  \
symbol date
aapl   2022-03-21 09:30:00  4030270  164.470001  164.110001  164.070007
       2022-03-21 09:35:00  2031681  165.179993  164.050003  165.009995
       2022-03-21 09:40:00  1637002  165.589996  165.009995  165.339996
       2022-03-21 09:45:00  1497955  165.521698  165.360001  165.024994
       2022-03-21 09:50:00  1863647  165.270004  165.035004  163.990005
...                             ...         ...         ...         ...
       2022-04-20 15:40:00  1015772  167.628494  167.500000  167.559998
       2022-04-20 15:45:00  1368005  167.940002  167.570007  167.809998
       2022-04-20 15:50:00  2150173  167.929993  167.809998  167.210007
       2022-04-20 15:55:00  3024593  167.389999  167.240005  167.229996
       2022-04-20 16:00:00        0  167.229996  167.229996  167.229996

                                   low
symbol date
aapl   2022-03-21 09:30:00  163.850006
       2022-03-21 09:35:00  164.020004
       2022-03-21 09:40:00  165.000000
       2022-03-21 09:45:00  164.979996
       2022-03-21 09:50:00  163.910004
...                                ...
       2022-04-20 15:40:00  167.369995
       2022-04-20 15:45:00  167.539993
       2022-04-20 15:50:00  167.050003
       2022-04-20 15:55:00  167.009995
       2022-04-20 16:00:00  167.229996

[1717 rows x 5 columns]

## To initialize multiple Ticker objects, use

In [4]:
symbols = ['fb', 'aapl', 'amzn', 'nflx', 'goog']

faang = Ticker(symbols)

faang.summary_detail

{'aapl': {'algorithm': None,
  'ask': 168.98,
  'askSize': 800,
  'averageDailyVolume10Day': 74511420,
  'averageVolume': 91570504,
  'averageVolume10days': 74511420,
  'beta': 1.187745,
  'bid': 0.0,
  'bidSize': 800,
  'currency': 'USD',
  'dayHigh': 168.86,
  'dayLow': 166.1,
  'dividendRate': 0.88,
  'dividendYield': 0.0053,
  'exDividendDate': '2022-02-04 00:00:00',
  'fiftyDayAverage': 167.4436,
  'fiftyTwoWeekHigh': 182.94,
  'fiftyTwoWeekLow': 122.25,
  'fiveYearAvgDividendYield': 1.11,
  'forwardPE': 25.453575,
  'fromCurrency': None,
  'lastMarket': None,
  'marketCap': 2729093103616,
  'maxAge': 1,
  'open': 168.76,
  'payoutRatio': 0.1434,
  'previousClose': 167.4,
  'priceHint': 2,
  'priceToSalesTrailing12Months': 7.213659,
  'regularMarketDayHigh': 168.86,
  'regularMarketDayLow': 166.1,
  'regularMarketOpen': 168.76,
  'regularMarketPreviousClose': 167.4,
  'regularMarketVolume': 66275582,
  'toCurrency': None,
  'tradeable': False,
  'trailingAnnualDividendRate': 0.865,
  'trailingAnnualDividendYield': 0.0051672645,
  'trailingPE': 27.80216,
  'twoHundredDayAverage': 158.771,
  'volume': 66275582},
 'amzn': {'algorithm': None,
  'ask': 3105.0,
  'askSize': 800,
  'averageDailyVolume10Day': 2831330,
  'averageVolume': 3784645,
  'averageVolume10days': 2831330,
  'beta': 1.119607,
  'bid': 3102.0,
  'bidSize': 900,
  'currency': 'USD',
  'dayHigh': 3152.05,
  'dayLow': 3072.33,
  'fiftyDayAverage': 3102.054,
  'fiftyTwoWeekHigh': 3773.08,
  'fiftyTwoWeekLow': 2671.45,
  'forwardPE': 42.824806,
  'fromCurrency': None,
  'lastMarket': None,
  'marketCap': 1566282874880,
  'maxAge': 1,
  'open': 3152.05,
  'payoutRatio': 0.0,
  'previousClose': 3162.31,
  'priceHint': 2,
  'priceToSalesTrailing12Months': 3.3337793,
  'regularMarketDayHigh': 3152.05,
  'regularMarketDayLow': 3072.33,
  'regularMarketOpen': 3152.05,
  'regularMarketPreviousClose': 3162.31,
  'regularMarketVolume': 2903554,
  'toCurrency': None,
  'tradeable': False,
  'trailingAnnualDividendRate': 0.0,
  'trailingAnnualDividendYield': 0.0,
  'trailingPE': 47.522915,
  'twoHundredDayAverage': 3308.2942,
  'volume': 2903554},
 'fb': {'algorithm': None,
  'ask': 201.98,
  'askSize': 800,
  'averageDailyVolume10Day': 22625890,
  'averageVolume': 38070568,
  'averageVolume10days': 22625890,
  'beta': 1.394117,
  'bid': 201.76,
  'bidSize': 1300,
  'currency': 'USD',
  'dayHigh': 214.16,
  'dayLow': 198.92,
  'fiftyDayAverage': 212.1792,
  'fiftyTwoWeekHigh': 384.33,
  'fiftyTwoWeekLow': 185.82,
  'forwardPE': 13.841161,
  'fromCurrency': None,
  'lastMarket': None,
  'marketCap': 544046120960,
  'maxAge': 1,
  'open': 213.605,
  'payoutRatio': 0.0,
  'previousClose': 217.31,
  'priceHint': 2,
  'priceToSalesTrailing12Months': 4.613336,
  'regularMarketDayHigh': 214.16,
  'regularMarketDayLow': 198.92,
  'regularMarketOpen': 213.605,
  'regularMarketPreviousClose': 217.31,
  'regularMarketVolume': 43036528,
  'toCurrency': None,
  'tradeable': False,
  'trailingAnnualDividendRate': 0.0,
  'trailingAnnualDividendYield': 0.0,
  'trailingPE': 14.554829,
  'twoHundredDayAverage': 307.8765,
  'volume': 43036528},
 'goog': {'algorithm': None,
  'ask': 2598.96,
  'askSize': 900,
  'averageDailyVolume10Day': 1049120,
  'averageVolume': 1530578,
  'averageVolume10days': 1049120,
  'beta': 1.060784,
  'bid': 0.0,
  'bidSize': 1200,
  'currency': 'USD',
  'dayHigh': 2638.47,
  'dayLow': 2557.881,
  'fiftyDayAverage': 2693.2642,
  'fiftyTwoWeekHigh': 3042.0,
  'fiftyTwoWeekLow': 2230.05,
  'forwardPE': 18.662033,
  'fromCurrency': None,
  'lastMarket': None,
  'marketCap': 1691799126016,
  'maxAge': 1,
  'open': 2625.68,
  'payoutRatio': 0.0,
  'previousClose': 2610.62,
  'priceHint': 2,
  'priceToSalesTrailing12Months': 6.5666,
  'regularMarketDayHigh': 2638.47,
  'regularMarketDayLow': 2557.881,
  'regularMarketOpen': 2625.68,
  'regularMarketPreviousClose': 2610.62,
  'regularMarketVolume': 1130469,
  'toCurrency': None,
  'tradeable': False,
  'trailingAnnualDividendRate': 0.0,
  'trailingAnnualDividendYield': 0.0,
  'trailingPE': 22.860771,
  'twoHundredDayAverage': 2785.322,
  'volume': 1130469},
 'nflx': {'algorithm': None,
  'ask': 0.0,
  'askSize': 1100,
  'averageDailyVolume10Day': 18748020,
  'averageVolume': 9678254,
  'averageVolume10days': 18748020,
  'beta': 0.969607,
  'bid': 218.3,
  'bidSize': 900,
  'currency': 'USD',
  'dayHigh': 248.45,
  'dayLow': 212.51,
  'fiftyDayAverage': 369.5658,
  'fiftyTwoWeekHigh': 700.99,
  'fiftyTwoWeekLow': 212.51,
  'forwardPE': 17.923138,
  'fromCurrency': None,
  'lastMarket': None,
  'marketCap': 100490330112,
  'maxAge': 1,
  'open': 245.2,
  'payoutRatio': 0.0,
  'previousClose': 348.61,
  'priceHint': 2,
  'priceToSalesTrailing12Months': 3.3837585,
  'regularMarketDayHigh': 248.45,
  'regularMarketDayLow': 212.51,
  'regularMarketOpen': 245.2,
  'regularMarketPreviousClose': 348.61,
  'regularMarketVolume': 132759913,
  'toCurrency': None,
  'tradeable': False,
  'trailingAnnualDividendRate': 0.0,
  'trailingAnnualDividendYield': 0.0,
  'trailingPE': 20.123667,
  'twoHundredDayAverage': 524.20825,
  'volume': 132759913}}